{% set version = "5.0" %}
{% set sha256 = "60cbc4bad079753721d32649545505362c754e121570ada4658b852a3a318d95" %}

package:
  name: boolean.py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/boolean.py/boolean_py-5.0.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
  imports:
    - boolean
  commands:
    - pip check

about:
  home: https://github.com/bastikr/boolean.py
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: >
    Define boolean algebras, create and parse boolean expressions and create custom
    boolean DSL.
  doc_url: https://booleanpy.readthedocs.io/
  dev_url: https://github.com/bastikr/boolean.py

extra:
  recipe-maintainers:
    - mbargull
