{% set name = "boolean.py" %}
{% set version = "5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('.', '_') }}-{{ version }}.tar.gz
  sha256: 60cbc4bad079753721d32649545505362c754e121570ada4658b852a3a318d95

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - boolean
  requires:
    - pip
    - pytest
  imports:
    - boolean
  commands:
    - pip check
    - pytest -v boolean

about:
  home: https://github.com/bastikr/boolean.py
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Implements boolean algebra in one module. 
  description: |
    "boolean.py" is a small library implementing a boolean algebra. It defines two base elements,
    TRUE and FALSE, and a Symbol class that can take on one of these two values. Calculations are
    done in terms of AND, OR and NOT - other compositions like XOR and NAND are not implemented but
    can be emulated with AND or and NOT. Expressions are constructed from parsed strings or in Python.
  doc_url: https://booleanpy.readthedocs.io
  dev_url: https://github.com/bastikr/boolean.py

extra:
  recipe-maintainers:
    - mbargull
